language: node_js

addons:
  apt:
    packages:
    - time

cache:
  npm: true

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

script:
  - sudo add-apt-repository -y ppa:rmescandon/yq
  - sudo apt-get -q update
  - sudo apt-get install yq -y
  - ./test/benchmark.sh

